config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "pages/dashboard", to: "pages#dashboard"

  resources :locations, only: %i[index show create destroy] do
    post :search, on: :collection
    post :distance, on: :collection
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
  attribute :raw_lonlat, :string
  validates :name, presence: true
  validates :raw_lonlat, presence: true
  validates :raw_lonlat, format: {
    with: /\A-?\d+(\.\d+)?\s-?\d+(\.\d+)?\z/,
    message: 'invalid'
  }
  validate :unique_record

  before_save :parse_lonlat

  enum kind: %i[town]

  def lonlat_string
    "#{lonlat.x}, #{lonlat.y}"
  end

  private

  def parse_lonlat
    coordinates = raw_lonlat.split(' ').map(&:to_f)
    self.lonlat = RGeo::Geographic.spherical_factory(srid: 4326).point(coordinates[0], coordinates[1])
  rescue StandardError => e
    Rails.logger.error(context: 'Location#parse_lonlat', message: 'Не удалось распарсить строку с координатами',
                       details: e.message)
    errors.add(:lonlat, 'could not parse lonlat coordinates')
  end

  def unique_record
    errors.add(:base, :not_unique_record) if Location.exists?(name: name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/distance_concern.rb
module DistanceConcern
  extend ActiveSupport::Concern

  def calculate_straight_distance(from, to)
    (from.lonlat.distance(to.lonlat)/1000).round(2)
  rescue StandardError
    raise DistanceHandler::DistanceCalculationError.new('DistanceConcern#calculate_distance')
  end
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
  skip_before_action :verify_authenticity_token, if: -> { request.format.json? }
  before_action :set_location, only: %i[show destroy]
  rescue_from DistanceHandler::DistanceDestinationsNotFoundError, DistanceHandler::DistanceCalculationError,
              with: :handle_distance_error

  include DistanceConcern

  def search
    @locations = Api::YandexGeocoder.cities_and_towns(params[:query])

    # render json: @locations.to_json
    respond_to do |format|
      format.json { render json: @locations.to_json }
      format.turbo_stream do
        html = render_to_string(partial: 'locations/search_result_wrapper',
                                locals: { locations: @locations[:result] || [],
                                          errors: @locations[:errors] || [],
                                          message: 'Не удалось получить локации' },
                                formats: [:html])
        render turbo_stream: [
          turbo_stream.update('search_result', html)
        ]
      end
    end
  end

  def index
    @locations = Location.all

    render json: @locations.to_json
  end

  def show
    render json: @location.to_json
  end

  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.turbo_stream do
          html = render_to_string(partial: 'locations/search_result_wrapper',
                                  locals: { locations: nil, errors: [] }, formats: [:html])
          render turbo_stream: [
            turbo_stream.update('search_result', html),
            turbo_stream.prepend('locations', @location),
            turbo_stream.update('distance_selectors', partial: 'locations/distance_selectors',
                                                      locals: { locations: Location.all }),
            turbo_stream.remove('locations_empty_notice')
          ]
        end
        format.json { render json: @location.to_json }
      else
        format.turbo_stream do
          html = render_to_string(partial: 'locations/search_result_wrapper',
                                  locals: { locations: nil, errors: @location.errors, message: 'Не удалось добавить локацию' }, formats: [:html])
          render turbo_stream: [
            turbo_stream.update('search_result', html)
          ]
        end
        format.json { render json: @location.errors.to_json, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @location.destroy
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update('locations', partial: 'locations/location', collection: Location.all,
                                             as: :location),
            turbo_stream.update('distance_selectors', partial: 'locations/distance_selectors',
                                                      locals: { locations: Location.all })
          ]
        end
        format.json { render json: @location.to_json }
      else
        format.json { render json: @location.errors.to_json, status: :unprocessable_entity }
      end
    end
  end

  def distance
    set_from_to
    @distance = calculate_straight_distance(@from, @to)

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update('distance_result', partial: 'locations/distance_result',
                                                 locals: { distance: @distance,
                                                           from: @from.name, to: @to.name, error: nil })
        ]
      end
      format.json { render json: { from: @from.name, to: @to.name, distance: @distance } }
    end
  end

  private

  def location_params
    params.require(:location).permit(:name, :raw_lonlat)
  end

  def set_location
    @location = Location.find(params[:id])
  end

  def set_from_to
    unless params[:from_id].present? && params[:to_id].present?
      raise DistanceHandler::DistanceDestinationsNotFoundError, 'LocationsController#set_from_to'
    end

    @from = Location.find(params[:from_id])
    @to = Location.find(params[:to_id])
  end

  def handle_distance_error(e)
    Rails.logger.error(message: e.message, context: e.context)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update('distance_result', partial: 'locations/distance_result',
                                                 locals: { distance: nil,
                                                           from: nil, to: nil, error: 'distance_error' })
        ]
      end
      format.json { render json: { error: e.message } }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    @locations = Location.all
    @location = Location.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
  def concat_name_and_coordinates(location)
    "#{location.name}, Координаты: #{location.lonlat_string}"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_error.html.erb
<div class='error-card'>
  <span class='large-text'><%= message %></span>
  <% errors.each do |error| %>
    <ul>
    <%if error.is_a?(Hash) %>
      <li class='text-red-500'><%=t("api.yandex_geocoder_error") %></li>
    <%end%>
      <%if error.respond_to?(:full_message) %>
        <li class='text-red-500'><%=error.full_message %></li>
      <%end%>
    </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Калькулятор расстояния</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="container w-full mx-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/locations/_distance_result.html.erb
<% if distance.present? || error.present? %>
  <div class='grid col-span-2'>
    <span class='header'>Последний результат</span>
    <% unless error.present? %>
      <div class="regular-text text-xl">Прямое расстояние от <span class='blue-text'><%= from %></span> до <span class='blue-text'><%= to %></span>: <span class='header'><%= distance %> км</span></div>
    <% end %>
    <% if error.present? %>
      <div class='text-red-500'><%= t('distance_error')%></div>
    <% end %>
  </div>
<% end %>

app/views/locations/_distance_selectors.html.erb
<div class='grid gap-y-2'>
  <span class="header">Расчет дистанции</span>
  <% if locations.any? %>
    <%= form_with url: distance_locations_path, method: :post, format: :turbo_stream, data: { turbo_frame: "distance_selectors" }, class: 'grid grid-flow-row gap-y-4' do |f| %>
      <div class='flex gap-2'>
        <span class='header'>Откуда: </span>
        <div class='w-full'>
          <%= f.select :from_id, locations.map { |location| [concat_name_and_coordinates(location), location.id] }, { :include_blank => false }, { :class => 'selector' } %>
        </div>
      </div>
      <div class='flex gap-2'>
        <span class='header'>Куда: </span>
        <%= f.select :to_id, locations.map { |location| [concat_name_and_coordinates(location) ,location.id] }, { :include_blank => false }, { :class => 'selector' } %>
      </div>
      <div>
        <%= f.submit 'Рассчитать', class: 'gray-button' %>
      </div>
    <% end %>
  <% else %>
    <div class='grid grid-flow-row'>
      <span class='regular-text'>Добавьте хотя бы одну локацию</span>
    </div>
  <% end %>
</div>

app/views/locations/_location.html.erb
<%= turbo_frame_tag location do %>
  <div class='location-card'>
    <span class='blue-text'><%= location.name %></span>
    <span class='regular-text'>Координаты (дол., шир.): <%= location.lonlat_string %></span>
    <span class='regular-text'>Добавлен: <%= l location.created_at, format: :long %></span>
    <%= button_to 'Удалить', location, method: :delete, data: { turbo_frame: 'locations' }, class: 'delete-button' %>
  </div>
<% end %>

app/views/locations/_search_field.html.erb
<div class='flex col-span-12'>
  <%= form_with url: search_locations_path, method: :post, format: :turbo_stream, data: { turbo_frame: "search_result" }, class: "flex gap-2" do |f| %>
    <%= f.text_field :query, placeholder: 'Введите название населенного пункта...', class: 'search-field', required: true, autocomplete: 'off' %>
  <%= f.submit 'Найти', class: 'gray-button' %>
  <% end %>
</div>

app/views/locations/_search_result.html.erb
  <div class='grid grid-flow-row px-4 py-2'>
    <span class='text-black'><%= location[:name] %></span>
    <span class='text-black'><%= location[:point] %></span>
    <%= form_for Location.build, format: :turbo_stream, data: { turbo_frame: 'locations' } do |f| %>
      <%= f.hidden_field :name, value: location[:name] %>
      <%= f.hidden_field :raw_lonlat, value: location[:point] %>
      <%= f.submit 'Добавить', class: 'add-button' %>
    <% end %>
  </div>

app/views/locations/_search_result_wrapper.html.erb
<% if errors.present? %>
  <div class='grid grid-cols-2 py-2'>
    <%= render partial: 'layouts/error', locals: { message: message || nil ,errors: errors } %>
  </div>
<% end %>
<% unless locations.nil? %>
  <% if locations.empty? %>
    <div class='grid grid-flow-row py-2'>
      <span class='regular-text'>Ничего не найдено</span>
    </div>
  <% end %>
  <% locations.each do |location| %>
    <%= render partial: 'locations/search_result', locals: { location: location } %>
  <% end %>
<% end %>

app/views/pages/dashboard.html.erb
<div class="grid grid-cols-12 p-4 gap-2">
  <span class="header flex col-span-12">Калькулятор прямого расстояния между двумя населенными пунктами</span>
  <%= turbo_frame_tag 'locations/search_field' %>
  <div class="grid grid-flow-row col-span-12">
    <%= render 'locations/search_field' %>
  </div>
  <%= turbo_frame_tag 'search_result', class: 'grid grid-flow-row col-span-12' do %>
    <%= render partial: 'locations/search_result_wrapper', locals: { locations: nil, errors: [] } %>
  <% end %>
  <div class="grid grid-flow-row col-span-12">
    <span class="header">Добавленные локации</span>
    <%= turbo_frame_tag 'locations_empty_notice', class: 'grid grid-flow-row' do %>
      <% if @locations.empty? %>
        <span class='regular-text mt-2'>Вы еще не добавили ни одной локации</span>
      <% end %>
    <% end %>
  </div>
  <%= turbo_frame_tag 'locations', class: 'grid col-span-12 grid-cols-2 gap-4' do %>
    <%= render @locations %>
  <% end %>
  <%= turbo_frame_tag 'distance_selectors',class: 'grid grid-flow-row col-span-12 gap-y-2' do %>
    <%= render 'locations/distance_selectors', locations: Location.all %>
  <% end %>
  <%= turbo_frame_tag 'distance_result', class: 'grid grid-flow-row col-span-12' do %>
    <%= render 'locations/distance_result', distance: nil, from: nil, to: nil, error: nil %>
  <% end %>
</div>